name: Deploy to Vercel

on:
  push:
    branches:
      - "main"
    paths: &paths
      - .github/workflows/deploy-*.yml
      - "!**/*.md"
      - "**"
  pull_request:
    paths: *paths
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

permissions: {}

jobs:
  preview:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    environment: vercel
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Set Build Information
        id: set-build-information
        run: echo "commit_sha_8_char=${GITHUB_SHA:0:8}" >> "$GITHUB_OUTPUT"

      - name: Build
        run: npm run build
        env:
          VITE_GIT_COMMIT_SHA_8_CHAR: ${{ steps.set-build-information.outputs.commit_sha_8_char }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=preview --token="${{ secrets.VERCEL_TOKEN }}"

      - name: Build Vercel Output
        run: vercel build --token="${{ secrets.VERCEL_TOKEN }}"
        env:
          VITE_GIT_COMMIT_SHA_8_CHAR: ${{ steps.set-build-information.outputs.commit_sha_8_char }}

      - name: Deploy Preview to Vercel
        run: vercel deploy --prebuilt --token="${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  live:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    environment: vercel
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Set Build Information
        id: set-build-information
        run: echo "commit_sha_8_char=${GITHUB_SHA:0:8}" >> "$GITHUB_OUTPUT"

      - name: Build
        run: npm run build
        env:
          VITE_GIT_COMMIT_SHA_8_CHAR: ${{ steps.set-build-information.outputs.commit_sha_8_char }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token="${{ secrets.VERCEL_TOKEN }}"

      - name: Build Vercel Output
        run: vercel build --prod --token="${{ secrets.VERCEL_TOKEN }}"
        env:
          VITE_GIT_COMMIT_SHA_8_CHAR: ${{ steps.set-build-information.outputs.commit_sha_8_char }}

      - name: Deploy Live Site to Vercel
        run: vercel deploy --prebuilt --prod --token="${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# Ensure the following secrets exist in `vercel` Environment Secrets.
# - VERCEL_TOKEN
# - VERCEL_ORG_ID
# - VERCEL_PROJECT_ID
